### ISSUE TITLE
Add utilization to UI + general enhancement 

### ISSUE THREAD

**Issue by amr55587** [amr55587/resource_assignment#3]
Hello Mohamed , 

We need to display in Page 2 
The resource utilization dictionary & (i.e the utilization of each resource) + the overall utilization
per the following python lines 

dict_assignment_resource_util=compute_utilization("1 JAN 2023","31 DEC 2023",RESOURCES_future)
print("dict_assignment_resource_util") ## Display this on UI
overall_future_utilization=sum(dict_assignment_resource_util.values()) / len(dict_assignment_resource_util.keys())
print("The foreseen utilization is ",overall_future_utilization) ## Display this on UI

-Can we Enhance the UI i..e make font larger, make bold , highlight the stats (numbers) in another color in both pages

Thanks alot 
Appreciating your work

**Comment by AI-MOO** [comment]
Hi Amr,  All the requirements are developed and added to the repo as you mentioned above:

Developed Features Summary : 
- The overall utilization can be shown now in the next page.
- The resources utilizations after the optimization process can be shown through a table.
- New Enhancements in the UI.
